name: Deploy production

on:
  push:
    branches:
      - main

permissions:
  id-token: write    # This is required for requesting the JWT
  contents: read     # This is required for actions/checkout

jobs:
  deploy:
    name: Deploy to production
    uses: ./.github/workflows/deploy.yml
    # Originally the workflow implementation was setup to use environment
    #  variables configured in the Github repository settings. However,
    #  after moving to a reusable action, it became ugly to pass those values
    #  into the called action due to this bug:
    #
    #    https://github.com/orgs/community/discussions/26671#discussioncomment-4295807
    #
    #  So now we're hardcoding the values here and using it as a manifest. Please see
    #  commit 1ec7a0346abc04b73c03e35c0e228e9dba14300c for the previous implementation.
    with:
      additional_certificate_arns: '[\"arn:aws:acm:us-east-1:510777193308:certificate/9a15e75a-1d74-4349-9ed0-65b0df777a22\"]'
      aws_region: us-east-1
      aws_replication_region: us-west-2
      aws_s3_terraform_state_object_key: production.tfstate
      dns_name: prod.aws-ecs-demo.carlucci.network
      environment_name: prod
      vpc_cidr_index: 0
    secrets:
      aws_assume_role_arn: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
      aws_s3_terraform_state_bucket_name: ${{ secrets.AWS_S3_TERRAFORM_STATE_BUCKET_NAME }}
